name: Terraform CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      # These environment variables will be picked up by any AWS CLI or SDK calls.
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Determine Environment Directory
        id: getenv
        run: |
          # For pull_request events, github.head_ref is available.
          if [ -n "${{ github.head_ref }}" ]; then
            echo "Using head_ref as environment: ${{ github.head_ref }}"
            echo "environment=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "Using ref_name as environment: ${{ github.ref_name }}"
            echo "environment=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Install TFLint
        run: |
          curl -sSLO https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh
          chmod +x install_linux.sh
          sudo ./install_linux.sh

      - name: Terraform Init, Validate & Plan
        run: |
          echo "Changing to environment directory: ${{ steps.getenv.outputs.environment }}"
          cd "${{ steps.getenv.outputs.environment }}"
          terraform init
          terraform validate
          terraform plan

  ansible:
    name: Run Ansible Playbooks
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Private Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Display Ansible Version
        run: ansible --version

      - name: Run Webserver Setup Playbook
        run: |
          cd ansible
          ansible-playbook -i aws_ec2.yaml webserver-setup.yml --private-key $HOME/.ssh/id_rsa -u ec2-user
